<a href="https://colab.research.google.com/github/Anshulmohan27/Python_Everything/blob/main/Pandas_Practice_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("muhammadmusharraf444/used-car-price-prediction-dataset")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'used-car-price-prediction-dataset' dataset.
Path to dataset files: /kaggle/input/used-car-price-prediction-dataset

In [5]:
import pandas as pd
import os

for file in os.listdir(path):
  print(file)

df = pd.read_csv(os.path.join(path, "quikr_car.csv"))
df.head(10) #displays first 10 rows

quikr_car.csv

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,Ask For Price,"22,000 kms",Petrol
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000","28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",Diesel
5,Ford EcoSport Titanium 1.5L TDCi,Ford,2015,Ask For Price,"59,000 kms",Diesel
6,Ford Figo,Ford,2012,"1,75,000","41,000 kms",Diesel
7,Hyundai Eon,Hyundai,2013,"1,90,000","25,000 kms",Petrol
8,Ford EcoSport Ambiente 1.5L TDCi,Ford,2016,"8,30,000","24,530 kms",Diesel
9,Maruti Suzuki Alto K10 VXi AMT,Maruti,2015,"2,50,000","60,000 kms",Petrol

In [6]:
df.shape #rows and columns

(892, 6)

In [7]:
df.columns #name of columns

Index(['name', 'company', 'year', 'Price', 'kms_driven', 'fuel_type'], dtype='object')

In [9]:
df.dtypes #columns type

name          object
company       object
year          object
Price         object
kms_driven    object
fuel_type     object
dtype: object

In [10]:
df.describe()

              name company  year          Price  kms_driven fuel_type
count          892     892   892            892         840       837
unique         525      48    61            274         258         3
top     Honda City  Maruti  2015  Ask For Price  45,000 kms    Petrol
freq            13     235   117             35          30       440

In [14]:
df.isna().sum()

name           0
company        0
year           0
Price          0
kms_driven    52
fuel_type     55
dtype: int64

In [22]:
df[df['fuel_type']=='Diesel'] #all diesel cars

,name,company,year,Price,kms_driven,fuel_type
1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",Diesel
5,Ford EcoSport Titanium 1.5L TDCi,Ford,2015,Ask For Price,"59,000 kms",Diesel
6,Ford Figo,Ford,2012,"1,75,000","41,000 kms",Diesel
8,Ford EcoSport Ambiente 1.5L TDCi,Ford,2016,"8,30,000","24,530 kms",Diesel
...,...,...,...,...,...,...
876,Maruti Suzuki Dzire,Maruti,2016,"4,50,000","2,500 kms",Diesel
880,Maruti Suzuki Swift Dzire Tour VDi,Maruti,2009,"2,50,000","51,000 kms",Diesel
885,Tata Indica V2 DLE BS III,Tata,2009,"1,10,000","30,000 kms",Diesel
888,Tata Zest XM Diesel,Tata,2018,"2,60,000","27,000 kms",Diesel
889,Mahindra Quanto C8,Mahindra,2013,"3,90,000","40,000 kms",Diesel

In [25]:
df['Price'] = pd.to_numeric(df['Price'], errors='coerce').astype('Int64')

In [29]:
df["Price"]

0      <NA>
1      <NA>
2      <NA>
3      <NA>
4      <NA>
       ...
887    <NA>
888    <NA>
889    <NA>
890    <NA>
891    <NA>
Name: Price, Length: 892, dtype: Int64

In [31]:
df[df['name'].str.contains('maruti', case=False, na=False)]

,name,company,year,Price,kms_driven,fuel_type
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,<NA>,"22,000 kms",Petrol
9,Maruti Suzuki Alto K10 VXi AMT,Maruti,2015,<NA>,"60,000 kms",Petrol
11,Maruti Suzuki Stingray VXi,Maruti,2015,<NA>,"30,000 kms",Petrol
19,Maruti Suzuki Alto 800,Maruti,2014,<NA>,"35,550 kms",Petrol
22,Maruti Suzuki Alto 800 Vxi,Maruti,2015,<NA>,"39,000 kms",Petrol
...,...,...,...,...,...,...
876,Maruti Suzuki Dzire,Maruti,2016,<NA>,"2,500 kms",Diesel
879,Maruti Suzuki Alto LXi BS III,Maruti,2005,<NA>,"65,000 kms",Petrol
880,Maruti Suzuki Swift Dzire Tour VDi,Maruti,2009,<NA>,"51,000 kms",Diesel
882,Maruti Suzuki Alto 800 Select Variant,Maruti,2015,<NA>,"70,000 kms",Petrol
883,Maruti Suzuki Ritz VXI ABS,Maruti,2011,<NA>,"50,000 kms",Petrol

In [32]:
df[(df['fuel_type'] == 'Petrol') & (df['kms_driven']>50000)] #would have worked if kms_driven were in numbers

TypeError: '>' not supported between instances of 'str' and 'int'

In [37]:
df.loc[df['year'].idxmin()]

name          9 SEATER MAHINDRA BOL
company                           9
year                           , Ac
Price                          <NA>
kms_driven                      NaN
fuel_type                       NaN
Name: 799, dtype: object

In [40]:
df['company'].unique()

array(['Hyundai', 'Mahindra', 'Maruti', 'Ford', 'Skoda', 'Audi', 'Toyota',
       'Renault', 'Honda', 'Datsun', 'Mitsubishi', 'Tata', 'Volkswagen',
       'I', 'Chevrolet', 'Mini', 'BMW', 'Nissan', 'Hindustan', 'Fiat',
       'Commercial', 'MARUTI', 'Force', 'Mercedes', 'Land', 'Yamaha',
       'selling', 'URJENT', 'Swift', 'Used', 'Jaguar', 'Jeep', 'tata',
       'Sale', 'very', 'Volvo', 'i', '2012', 'Well', 'all', '7', '9',
       'scratch', 'urgent', 'sell', 'TATA', 'Any', 'Tara'], dtype=object)

In [41]:
df['fuel_type'].value_counts()

fuel_type
Petrol    440
Diesel    395
LPG         2
Name: count, dtype: int64

In [42]:
df['company'].value_counts()

company
Maruti        235
Hyundai       145
Mahindra      100
Tata           74
Honda          61
Toyota         39
Chevrolet      35
Renault        34
Ford           31
Volkswagen     20
Skoda          13
Audi           11
Mini            8
Datsun          8
BMW             8
Mitsubishi      6
Mercedes        6
Nissan          6
Commercial      6
Force           4
Fiat            4
I               3
Hindustan       3
tata            3
Jaguar          2
Used            2
Sale            2
MARUTI          2
urgent          2
URJENT          1
Land            1
Yamaha          1
Jeep            1
Swift           1
selling         1
very            1
i               1
2012            1
Well            1
Volvo           1
all             1
7               1
9               1
scratch         1
sell            1
TATA            1
Any             1
Tara            1
Name: count, dtype: int64

In [46]:
df['company'].value_counts().sort_values(ascending = False).head(5)

company
Maruti      235
Hyundai     145
Mahindra    100
Tata         74
Honda        61
Name: count, dtype: int64

In [47]:
df.groupby('fuel_type')['kms_driven'].mean()

TypeError: agg function failed [how->mean,dtype->object]

In [51]:
df.groupby('year').size()

year
, Ac    1
...     3
/-Rs    1
150k    1
1995    2
       ..
t xe    1
tion    1
ture    1
zest    1
zire    1
Length: 61, dtype: int64

In [53]:
df['kms_driven'] = (
    df['kms_driven']
    .str.replace(',', '').str.replace('kms','')
)

In [54]:
df['kms_driven'] = pd.to_numeric(
    df['kms_driven'],
    errors='coerce'
)

In [55]:
df['kms_driven'].head()

0    45000.0
1       40.0
2    22000.0
3    28000.0
4    36000.0
Name: kms_driven, dtype: float64

In [57]:
df["most_driven"]=df.groupby('company')['kms_driven'].rank(method = 'dense', ascending=False)
df[df['most_driven']==2]

,name,company,year,Price,kms_driven,fuel_type,most_driven
47,Datsun Redi GO S,Datsun,2017,<NA>,16000.0,Petrol,2.0
49,Mitsubishi Pajero Sport Limited Edition,Mitsubishi,2015,<NA>,47000.0,Diesel,2.0
73,Mini Cooper S 1.6,Mini,2013,<NA>,13000.0,Petrol,2.0
74,Datsun Redi GO S,Datsun,2017,<NA>,16000.0,Petrol,2.0
94,BMW 3 Series 320i,BMW,2011,<NA>,60500.0,Petrol,2.0
189,Mini Cooper S 1.6,Mini,2013,<NA>,13000.0,Petrol,2.0
218,Force Motors Force One LX ABS 7 STR,Force,2015,<NA>,3200.0,Diesel,2.0
229,Mitsubishi Pajero Sport Limited Edition,Mitsubishi,2015,<NA>,47000.0,Diesel,2.0
246,Force Motors Force One LX ABS 7 STR,Force,2015,<NA>,3200.0,Diesel,2.0
249,Mini Cooper S,Mini,2013,<NA>,13000.0,Petrol,2.0
270,Nissan Terrano XL D Plus,Nissan,2015,<NA>,60000.0,Diesel,2.0
272,Renault Duster 85 PS RxE Diesel,Renault,2014,<NA>,59000.0,Diesel,2.0
297,Mini Cooper S 1.6,Mini,2013,<NA>,13000.0,Petrol,2.0
298,Mini Cooper S 1.6,Mini,2013,<NA>,13000.0,Petrol,2.0
300,Mini Cooper S,Mini,2013,<NA>,13000.0,Petrol,2.0
303,Mahindra Scorpio VLX Special Edition BS III,Mahindra,2004,<NA>,160000.0,Diesel,2.0
370,Force Motors Force One LX ABS 7 STR,Force,2015,<NA>,3200.0,Diesel,2.0
379,Maruti Suzuki Swift Dzire Tour LDi,Maruti,2016,<NA>,166000.0,Diesel,2.0
399,Mercedes Benz C Class 200 CDI Classic,Mercedes,2002,<NA>,41000.0,Petrol,2.0
443,Honda Amaze 1.5 E i DTEC,Honda,2016,<NA>,160000.0,Diesel,2.0
474,Hyundai Xcent Base 1.1 CRDi,Hyundai,2016,<NA>,140000.0,Diesel,2.0
510,Jaguar XE XE Portfolio,Jaguar,2016,<NA>,8500.0,Petrol,2.0
578,Chevrolet Beat LS Diesel,Chevrolet,2016,<NA>,95000.0,Diesel,2.0
589,Tata Indigo eCS LX TDI BS III,Tata,2014,<NA>,195000.0,Diesel,2.0
620,Skoda Octavia Classic 1.9 TDI MT,Skoda,2006,<NA>,65000.0,Diesel,2.0
678,Audi A4 2.0 TDI 177bhp Premium,Audi,2016,<NA>,44000.0,Diesel,2.0
700,Volkswagen Vento Comfortline Diesel,Volkswagen,2011,<NA>,95000.0,Diesel,2.0
768,Hindustan Motors Ambassador Classic Mark 4 – Befo,Hindustan,1995,<NA>,37000.0,Petrol,2.0
769,Ford Fusion 1.4 TDCi Diesel,Ford,2007,<NA>,85455.0,Diesel,2.0
772,Fiat Linea Emotion 1.4 L T Jet Petrol,Fiat,2009,<NA>,64000.0,Petrol,2.0
886,Toyota Corolla Altis,Toyota,2009,<NA>,132000.0,Petrol,2.0