<a href="https://colab.research.google.com/github/Anshulmohan27/Python_Everything/blob/main/Pandas_Practice_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import kagglehub
import os
import pandas as pd

# Download latest version
path = kagglehub.dataset_download("juanschafle/cyber-attack-detection-using-network-traffic")

print("Path to dataset files:", path)

for file in os.listdir(path):
  print(file)

Downloading to /root/.cache/kagglehub/datasets/juanschafle/cyber-attack-detection-using-network-traffic/1.archive...

100%|██████████| 785k/785k [00:00<00:00, 87.4MB/s]

Extracting files...
Path to dataset files: /root/.cache/kagglehub/datasets/juanschafle/cyber-attack-detection-using-network-traffic/versions/1
cyber_attack_dataset_100000.csv

In [ ]:
df = pd.read_csv(os.path.join(path, 'cyber_attack_dataset_100000.csv'))

In [ ]:
df.head()

,duration,src_bytes,dst_bytes,packet_count,protocol,failed_logins,attack_type
0,1,8605,418,631,TCP,0,DDoS
1,1,499,148,131,UDP,0,PortScan
2,10,370,160,105,UDP,0,PortScan
3,2,5138,320,666,TCP,0,DDoS
4,36,524,467,58,UDP,10,BruteForce

In [ ]:
df.head(10)

,duration,src_bytes,dst_bytes,packet_count,protocol,failed_logins,attack_type
0,1,8605,418,631,TCP,0,DDoS
1,1,499,148,131,UDP,0,PortScan
2,10,370,160,105,UDP,0,PortScan
3,2,5138,320,666,TCP,0,DDoS
4,36,524,467,58,UDP,10,BruteForce
5,7,236,71,211,UDP,0,PortScan
6,17,424,997,45,TCP,0,Normal
7,49,199,1810,7,TCP,0,Normal
8,19,107,1545,7,UDP,0,Normal
9,19,1555,1995,5,UDP,0,Normal

In [ ]:
df.tail(15)

,duration,src_bytes,dst_bytes,packet_count,protocol,failed_logins,attack_type
99985,18,1370,195,42,TCP,0,Normal
99986,56,345,1322,50,TCP,0,Normal
99987,17,151,124,50,UDP,6,BruteForce
99988,21,359,326,84,UDP,3,BruteForce
99989,3,178,22,195,TCP,0,PortScan
99990,29,723,1138,46,TCP,0,Normal
99991,11,1599,414,34,TCP,0,Normal
99992,42,277,1470,40,TCP,0,Normal
99993,38,1231,1907,33,TCP,0,Normal
99994,10,663,61,46,UDP,7,BruteForce
99995,10,380,41,143,TCP,0,PortScan
99996,2,153,146,85,TCP,0,PortScan
99997,37,161,114,61,UDP,10,BruteForce
99998,4,142,69,73,TCP,0,PortScan
99999,2,8514,445,681,TCP,0,DDoS

In [ ]:
df.shape

(100000, 7)

In [ ]:
df.columns

Index(['duration', 'src_bytes', 'dst_bytes', 'packet_count', 'protocol',
       'failed_logins', 'attack_type'],
      dtype='object')

In [ ]:
df.dtypes

duration          int64
src_bytes         int64
dst_bytes         int64
packet_count      int64
protocol         object
failed_logins     int64
attack_type      object
dtype: object

In [ ]:
df.isna().sum()

duration         0
src_bytes        0
dst_bytes        0
packet_count     0
protocol         0
failed_logins    0
attack_type      0
dtype: int64

In [ ]:
len(df)

100000

In [ ]:
df['protocol'].unique()

array(['TCP', 'UDP'], dtype=object)

In [ ]:
df['attack_type'].unique()

array(['DDoS', 'PortScan', 'BruteForce', 'Normal'], dtype=object)

In [ ]:
df['protocol'].value_counts()

protocol
TCP    50186
UDP    49814
Name: count, dtype: int64

In [ ]:
df['attack_type'].value_counts()

attack_type
DDoS          25077
BruteForce    25039
PortScan      25008
Normal        24876
Name: count, dtype: int64

In [ ]:
print(df['duration'].mean())

16.46272

In [ ]:
df['src_bytes'].agg(['max','min'])

max    10000
min       50
Name: src_bytes, dtype: int64

In [ ]:
df[df['failed_logins']>0]

,duration,src_bytes,dst_bytes,packet_count,protocol,failed_logins,attack_type
4,36,524,467,58,UDP,10,BruteForce
25,27,809,282,89,UDP,8,BruteForce
30,38,310,53,67,UDP,6,BruteForce
32,27,963,464,90,UDP,7,BruteForce
37,31,235,160,55,UDP,9,BruteForce
...,...,...,...,...,...,...,...
99977,23,127,451,92,UDP,7,BruteForce
99987,17,151,124,50,UDP,6,BruteForce
99988,21,359,326,84,UDP,3,BruteForce
99994,10,663,61,46,UDP,7,BruteForce
99997,37,161,114,61,UDP,10,BruteForce

In [ ]:
df[df['protocol']=='TCP']

,duration,src_bytes,dst_bytes,packet_count,protocol,failed_logins,attack_type
0,1,8605,418,631,TCP,0,DDoS
3,2,5138,320,666,TCP,0,DDoS
6,17,424,997,45,TCP,0,Normal
7,49,199,1810,7,TCP,0,Normal
10,7,480,44,281,TCP,0,PortScan
...,...,...,...,...,...,...,...
99993,38,1231,1907,33,TCP,0,Normal
99995,10,380,41,143,TCP,0,PortScan
99996,2,153,146,85,TCP,0,PortScan
99998,4,142,69,73,TCP,0,PortScan
99999,2,8514,445,681,TCP,0,DDoS

In [ ]:
df[df['packet_count']>100]

,duration,src_bytes,dst_bytes,packet_count,protocol,failed_logins,attack_type
0,1,8605,418,631,TCP,0,DDoS
1,1,499,148,131,UDP,0,PortScan
2,10,370,160,105,UDP,0,PortScan
3,2,5138,320,666,TCP,0,DDoS
5,7,236,71,211,UDP,0,PortScan
...,...,...,...,...,...,...,...
99982,3,176,171,106,TCP,0,PortScan
99984,3,4054,142,832,TCP,0,DDoS
99989,3,178,22,195,TCP,0,PortScan
99995,10,380,41,143,TCP,0,PortScan
99999,2,8514,445,681,TCP,0,DDoS

In [ ]:
df[df['src_bytes']>df['dst_bytes']]

,duration,src_bytes,dst_bytes,packet_count,protocol,failed_logins,attack_type
0,1,8605,418,631,TCP,0,DDoS
1,1,499,148,131,UDP,0,PortScan
2,10,370,160,105,UDP,0,PortScan
3,2,5138,320,666,TCP,0,DDoS
4,36,524,467,58,UDP,10,BruteForce
...,...,...,...,...,...,...,...
99995,10,380,41,143,TCP,0,PortScan
99996,2,153,146,85,TCP,0,PortScan
99997,37,161,114,61,UDP,10,BruteForce
99998,4,142,69,73,TCP,0,PortScan
99999,2,8514,445,681,TCP,0,DDoS

In [ ]:
df['packet_count'].mean()

np.float64(202.55077)

In [ ]:
df.sort_values('src_bytes', ascending = False).head(10)

,duration,src_bytes,dst_bytes,packet_count,protocol,failed_logins,attack_type
14308,4,10000,89,580,TCP,0,DDoS
66436,3,10000,112,743,TCP,0,DDoS
40723,5,9999,83,233,TCP,0,DDoS
94492,5,9999,167,531,TCP,0,DDoS
71700,1,9998,284,315,TCP,0,DDoS
83039,4,9998,127,744,TCP,0,DDoS
11716,5,9998,50,933,TCP,0,DDoS
4363,3,9998,371,448,TCP,0,DDoS
4496,1,9998,428,656,TCP,0,DDoS
74297,1,9998,171,243,TCP,0,DDoS

In [ ]:
df.groupby('protocol')['src_bytes'].mean()

protocol
TCP    3701.338481
UDP     726.853836
Name: src_bytes, dtype: float64

In [ ]:
#Mean dst_bytes by protocol
df.groupby('protocol')['dst_bytes'].mean()

protocol
TCP    427.857072
UDP    424.472397
Name: dst_bytes, dtype: float64

In [ ]:
#Total packet count by protocol
df.groupby('protocol')['packet_count'].sum()

protocol
TCP    16365142
UDP     3889935
Name: packet_count, dtype: int64

In [ ]:
df['duration'].median()

10.0

In [ ]:
avg_dur = df['duration'].mean()
df[df['duration']>avg_dur]

,duration,src_bytes,dst_bytes,packet_count,protocol,failed_logins,attack_type
4,36,524,467,58,UDP,10,BruteForce
6,17,424,997,45,TCP,0,Normal
7,49,199,1810,7,TCP,0,Normal
8,19,107,1545,7,UDP,0,Normal
9,19,1555,1995,5,UDP,0,Normal
...,...,...,...,...,...,...,...
99988,21,359,326,84,UDP,3,BruteForce
99990,29,723,1138,46,TCP,0,Normal
99992,42,277,1470,40,TCP,0,Normal
99993,38,1231,1907,33,TCP,0,Normal
99997,37,161,114,61,UDP,10,BruteForce

In [ ]:
#Percentage of records per attack type

df.groupby('attack_type').size()*100/len(df)
df["attack_type"].value_counts(normalize=True) * 100

attack_type
DDoS          25.077
BruteForce    25.039
PortScan      25.008
Normal        24.876
Name: proportion, dtype: float64

In [ ]:
#Avg duration per attack type
df.groupby('attack_type')['duration'].mean()

attack_type
BruteForce    25.038620
DDoS           3.005224
Normal        32.424666
PortScan       5.493122
Name: duration, dtype: float64

In [ ]:
#Avg packet count per attack type
df.groupby('attack_type')['packet_count'].mean()

attack_type
BruteForce     55.016135
DDoS          551.596004
Normal         27.508924
PortScan      174.377919
Name: packet_count, dtype: float64

In [ ]:
#Max src_bytes per protocol
df.groupby('protocol')['src_bytes'].max()

protocol
TCP    10000
UDP     3000
Name: src_bytes, dtype: int64

In [ ]:
#Min dst_bytes per protocol
df.groupby('protocol')['dst_bytes'].min()

protocol
TCP    20
UDP    20
Name: dst_bytes, dtype: int64

In [ ]:
#Count records by protocol and attack_type
df.groupby(['protocol','attack_type']).size()

protocol  attack_type
TCP       DDoS           25077
          Normal         12543
          PortScan       12566
UDP       BruteForce     25039
          Normal         12333
          PortScan       12442
dtype: int64

In [ ]:
#Total src_bytes per attack_type
df.groupby('attack_type')['src_bytes'].size()

attack_type
BruteForce    25039
DDoS          25077
Normal        24876
PortScan      25008
Name: src_bytes, dtype: int64

In [ ]:
#Total dst_bytes per attack_type
df.groupby('attack_type')['dst_bytes'].size()

attack_type
BruteForce    25039
DDoS          25077
Normal        24876
PortScan      25008
Name: dst_bytes, dtype: int64

In [ ]:
#Protocol with highest avg packet count
df.groupby('protocol')['packet_count'].mean().head(1)

protocol
TCP    326.089786
Name: packet_count, dtype: float64

In [ ]:
#Attack type with highest avg failed logins
df.groupby('attack_type')['failed_logins'].mean().head(1)

attack_type
BruteForce    6.511921
Name: failed_logins, dtype: float64

In [ ]:
#Attack type with lowest avg duration
df.groupby('attack_type')['duration'].mean().tail(1)

attack_type
PortScan    5.493122
Name: duration, dtype: float64

In [ ]:
#Mean, median, min, max duration by protocol
df.groupby('protocol')['duration'].agg(['mean', 'median', 'min','max'])

               mean  median  min  max
protocol
TCP       11.013330     4.0    1   60
UDP       21.952804    21.0    1   60

In [ ]:
#Top 3 attack types by total packet count
df.groupby('attack_type')['packet_count'].size().head(3)

attack_type
BruteForce    25039
DDoS          25077
Normal        24876
Name: packet_count, dtype: int64

In [ ]:
#Create a column categorizing packet count:
#Low (<50)
#Medium (50-150)
#High (>150)
def assign_cat(df):
    if df['packet_count'] < 50:
        return 'Low'
    elif (df['packet_count'] >= 50) & (df['packet_count'] <150):
        return 'Medium'
    elif df['packet_count'] >= 150:
        return 'High'

df['packet_category'] = df.apply(assign_cat, axis=1)
df[['packet_category', 'packet_count']]

      packet_category  packet_count
0                High           631
1              Medium           131
2              Medium           105
3                High           666
4              Medium            58
...               ...           ...
99995          Medium           143
99996          Medium            85
99997          Medium            61
99998          Medium            73
99999            High           681

[100000 rows x 2 columns]

In [ ]:
#Which protocol generates the most traffic overall?
df['total_traffic'] = df['dst_bytes'] + df['src_bytes']
df.groupby('protocol')['total_traffic'].size()

protocol
TCP    50186
UDP    49814
Name: total_traffic, dtype: int64